package com.zoe.wan.android.jiangnan.common

object Constants {
    const val SP_SETTINGS_SERVER = "SP_SETTINGS_SERVER"
    const val SP_SETTINGS_TOKEN = "SP_SETTINGS_TOKEN"
    const val SP_SETTINGS_PASSWORD = "SP_SETTINGS_PASSWORD"
    const val SP_SETTINGS_EXPIRED_TIME = "SP_SETTINGS_EXPIRED_TIME"
    const val SP_SETTINGS_ACCESS_TOKEN = "SP_SETTINGS_ACCESS_TOKEN"
    const val SP_SETTINGS_REFRESH_TOKEN = "SP_SETTINGS_REFRESH_TOKEN"
}